title: OKTW Network
email: admin@oktw.network

description: >-
  A Website for OKTW Network
  
baseurl: ""
url: "https://oktw.network"

languages: ["tw","en"]
exclude_from_localizations: ["javascript", "images", "css"]

github_username:  OKTW-Network

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-sass-converter